# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_time', models.TimeField(verbose_name='\u5230\u7ad9\u65f6\u95f4')),
                ('out_time', models.TimeField(verbose_name='\u53d1\u8f66\u65f6\u95f4')),
                ('sequences', models.IntegerField(verbose_name='\u53d1\u8f66\u987a\u5e8f')),
                ('station_type', models.IntegerField(choices=[(0, '\u59cb\u53d1\u7ad9'), (1, '\u4e2d\u9014\u7ad9'), (2, '\u7ec8\u70b9\u7ad9')], default=1, verbose_name='\u8f66\u7ad9\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='RawTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8f66\u6b21')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u7ad9\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_no', models.CharField(max_length=50, verbose_name='\u8f66\u6b21')),
                ('status', models.IntegerField(choices=[(0, '\u5df2\u505c\u7528'), (1, '\u4f7f\u7528\u4e2d'), (2, '\u672a\u77e5')], default=1, verbose_name='\u72b6\u6001')),
                ('stations', models.ManyToManyField(through='trains.Membership', to='trains.Station')),
            ],
        ),
        migrations.AddField(
            model_name='rawtrain',
            name='std_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Train', verbose_name='\u6807\u51c6\u8f66\u6b21'),
        ),
        migrations.AddField(
            model_name='membership',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Station', verbose_name='\u7ad9\u540d'),
        ),
        migrations.AddField(
            model_name='membership',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Train', verbose_name='\u8f66\u6b21'),
        ),
    ]
